name: Docker Build and Push with Tags

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      COMMIT_SHA: ${{ github.sha }}
      SHORT_SHA: ${{ github.sha }}  # or use: ${{ github.sha::7 }}
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push App 1
      - name: Build and push container_1 (app1.py)
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:app1-${BRANCH_NAME}-${SHORT_SHA}
          echo "Building $IMAGE_TAG"
          docker build -t $IMAGE_TAG ./container_1
          docker push $IMAGE_TAG

      # Build and push App 2
      - name: Build and push container_2 (app2.py)
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:app2-${BRANCH_NAME}-${SHORT_SHA}
          echo "Building $IMAGE_TAG"
          docker build -t $IMAGE_TAG ./container_2
          docker push $IMAGE_TAG
